name: Sync Submodules

# on:
#     schedule:
#       - cron: '0 0 * * *'  # 每天零点执行，可以根据需求调整

on:
    workflow_dispatch:      
jobs:
  sync-submodules:
    runs-on: ubuntu-large-18.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: List Submodules
      run: |
        git submodule update --remote --merge
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply. github.com"
        git add .
        git commit -m "Sync submodules to latest"
        git push
