name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      group: Default
      labels: ubuntu-large-18.04

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive  # 递归克隆子模块      

    # - name: Run submodule check
    #   run: |
    #     chmod +x check_submodule.sh
    #     bash check_submodule.sh
    #     if [[ "$SUBMODULE_UPDATED" == "true" ]]; then
    #       # 在这里添加触发 CI/CD 流程的命令
    #     fi
    #   env:
    #     SUBMODULE_UPDATED: ${{ env.SUBMODULE_UPDATED }}

    # - name: Create temporary directory
    #   run: mkdir -p temp
    #   working-directory: .github/scripts

    - name: Download toolchain installation package and update apt packages
      run: |
        wget -q https://github.com/Comet959/-ok8mq-jailhouse-linux/releases/download/toolchain/aarch64-poky-linux-aa
        wget -q https://github.com/Comet959/-ok8mq-jailhouse-linux/releases/download/toolchain/aarch64-poky-linux-ab
        wget -q https://github.com/Comet959/-ok8mq-jailhouse-linux/releases/download/toolchain/aarch64-poky-linux-ac
        cat aarch64-poky-linux-* > cross-compiler-aarch64-poky-linux
        unzip cross-compiler-aarch64-poky-linux
        chmod +x ╜╗▓ц▒р╥ы╣д╛▀/fsl-imx-xwayland-glibc-x86_64-meta-toolchain-qt5-aarch64-toolchain-5.4-zeus.sh
        sudo apt-get update
        sudo apt-get install expect -y
        sudo apt-get install openssh-server vim git fakeroot make automake \
                         autoconf libtool libssl-dev bc dosfstools mtools parted iproute2 gcc kmod -y
        chmod +x ./install_compiler.sh
      working-directory: .github/scripts

    - name: Install the aarch64-poky-linux toolchain
      run: |
        ./install_compiler.sh

      working-directory: .github/scripts
    
    - name: Delete Compiler Dir
      run: |
        rm -rf ╜╗▓ц▒р╥ы╣д╛▀ 
      working-directory: .github/scripts

    - name: Set up compiler in PATH and Build
      run: |
        gcc --version
        . /opt/fsl-imx-xwayland/5.4-zeus/environment-setup-aarch64-poky-linux
        . environment-4gddr-setup-sourcetree
        make
      working-directory: .
