name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      group: Default-Larger-Runners
      labels: ubuntu-large

    steps:

    - name: Checkout code with submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive  # 递归克隆子模块      

    # - name: Run submodule check
    #   run: |
    #     chmod +x check_submodule.sh
    #     bash check_submodule.sh
    #     if [[ "$SUBMODULE_UPDATED" == "true" ]]; then
    #       # 在这里添加触发 CI/CD 流程的命令
    #     fi
    #   env:
    #     SUBMODULE_UPDATED: ${{ env.SUBMODULE_UPDATED }}

    # - name: Create temporary directory
    #   run: mkdir -p temp
    #   working-directory: .github/scripts



    - name: Download install_compiler.sh
      run: |
        wget https://github.com/Comet959/-ok8mq-jailhouse-linux/releases/download/toolchain/aarch64-poky-linux-aa
        wget https://github.com/Comet959/-ok8mq-jailhouse-linux/releases/download/toolchain/aarch64-poky-linux-ab
        wget https://github.com/Comet959/-ok8mq-jailhouse-linux/releases/download/toolchain/aarch64-poky-linux-ac
        cat aarch64-poky-linux-* > cross-compiler-aarch64-poky-linux
        unzip cross-compiler-aarch64-poky-linux
        chmod +x ╜╗▓ц▒р╥ы╣д╛▀/fsl-imx-xwayland-glibc-x86_64-meta-toolchain-qt5-aarch64-toolchain-5.4-zeus.sh
        sudo apt-get install expect -y
        chmod +x ./install_compiler.sh

      working-directory: .github/scripts

    - name: Exec install_compiler.sh
      run: |
        ./install_compiler.sh

      working-directory: .github/scripts

    # - name: Install custom compiler
    #   run: |
    #     ./install_compiler.sh
    #   working-directory: .github/scripts
    
    - name: Delete compiler
      run: |
        rm -rf ╜╗▓ц▒р╥ы╣д╛▀ 
      working-directory: .github/scripts

    - name: Set up compiler in PATH and build
      run: |
        . .github/scripts/environment-setup-aarch64-poky-linux
        . environment-4gddr-setup-sourcetree
        ls -lh
        make
      working-directory: .

    # 添加其他测试、部署等步骤，根据需要进行扩展
