name: Update Submodules

on:
  push:
    branches:
      - main
jobs:
  update_sdk:
    runs-on: ubuntu-large-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup SSH Keys and known_hosts
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
            mkdir -p ~/.ssh
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Update submodules
        run: |
          git submodule update --init --remote
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Update SDK" || exit 0
          git push || exit 0          

